# Generated by Django 2.2.1 on 2019-07-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='confirmation_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='contact',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
